[versions]
dokka = "2.2.0"
kotest = "6.1.11"
kotlin = "2.3.20"
kotlinter = "5.4.2"
logback = "1.5.32"
maven-publish = "0.36.0"
versions = "0.54.0"

[libraries]
gradle-versions-plugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versions" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinter-gradle = { module = "org.jmailen.gradle:kotlinter-gradle", version.ref = "kotlinter" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
